### ISSUE TITLE
Frequent Error with date_select Input and `select_:year

### ISSUE THREAD

**Issue by mateuszbialowas** [formtastic/formtastic#1383]
Hey,

This is my input in `active_admin`:

```ruby
input :expires_at, as: :date_select, start_year: 1.year.ago.year, end_year: 10.years.from_now.year
```

Unfortunately, sometimes it raises an error:

```
ActionView::Template::Error: undefined method `select_:year' for #<ActionView::Base:0x00000000181690>
formtastic (5.0.0) lib/formtastic/inputs/base/timeish.rb:170:in `fragment_input_html'
formtastic (5.0.0) lib/formtastic/inputs/base/timeish.rb:106:in `block (4 levels) in to_html'
actionview (7.1.3.4) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.3.4) lib/action_view/buffers.rb:75:in `capture'
```

Do you know how I can fix it?
It occurs frequently, in production also, not only in development.

### Full backtrace
```
>Backtrace</h1>
lib/formtastic/inputs/base/timeish.rb:170 fragment_input_html |  
lib/formtastic/inputs/base/timeish.rb:106 block (4 levels) in to_html |  
lib/action_view/helpers/capture_helper.rb:50 block in capture |  
lib/action_view/buffers.rb:75 capture |  
lib/action_view/helpers/capture_helper.rb:50 capture |  
lib/formtastic/inputs/base/timeish.rb:132 fragment_wrapping |  
lib/formtastic/inputs/base/timeish.rb:104 block (3 levels) in to_html |  
lib/formtastic/inputs/base/timeish.rb:103 map |  
lib/formtastic/inputs/base/timeish.rb:103 block (2 levels) in to_html |  
lib/action_view/helpers/capture_helper.rb:50 block in capture |  
lib/action_view/buffers.rb:75 capture |  
lib/action_view/helpers/capture_helper.rb:50 capture |  
lib/formtastic/inputs/base/timeish.rb:205 fragments_wrapping |  
lib/formtastic/inputs/base/timeish.rb:99 block in to_html |  
lib/action_view/helpers/capture_helper.rb:50 block in capture |  
lib/action_view/buffers.rb:75 capture |  
lib/action_view/helpers/capture_helper.rb:50 capture |  
lib/formtastic/inputs/base/wrapping.rb:12 input_wrapping |  
lib/active_admin/form_builder.rb:7 input_wrapping |  
lib/formtastic/inputs/base/timeish.rb:98 to_html |  
lib/formtastic/helpers/input_helper.rb:240 input |  
lib/arbre/rails/forms.rb:31 proxy_call_to_form |  
lib/active_admin/views/components/active_admin_form.rb:72 input |  
app/global_admin/admin/accounts.rb:84 block (3 levels) in <main> |  
lib/active_admin/views/components/active_admin_form.rb:54 block (2 levels) in inputs |  
lib/action_view/helpers/capture_helper.rb:50 block in capture |  
lib/action_view/buffers.rb:75 capture |  
lib/action_view/helpers/capture_helper.rb:50 capture |  
lib/active_admin/views/components/active_admin_form.rb:53 block in inputs |  
lib/arbre/element/builder_methods.rb:32 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/active_admin/views/components/active_admin_form.rb:59 inputs |  
app/global_admin/admin/accounts.rb:75 block (2 levels) in <main> |  
lib/active_admin/views/components/active_admin_form.rb:36 instance_eval |  
lib/active_admin/views/components/active_admin_form.rb:36 build |  
lib/arbre/element/builder_methods.rb:29 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/arbre/element/builder_methods.rb:15 active_admin_form_for |  
lib/active_admin/views/pages/form.rb:26 main_content |  
lib/active_admin/views/pages/base.rb:105 block (2 levels) in build_main_content_wrapper |  
lib/arbre/element/builder_methods.rb:32 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/arbre/element/builder_methods.rb:15 div |  
lib/active_admin/views/pages/base.rb:104 block in build_main_content_wrapper |  
lib/arbre/element/builder_methods.rb:32 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/arbre/element/builder_methods.rb:15 div |  
lib/active_admin/views/pages/base.rb:103 build_main_content_wrapper |  
lib/active_admin/views/pages/base.rb:87 block in build_page_content |  
lib/arbre/element/builder_methods.rb:32 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/arbre/element/builder_methods.rb:15 div |  
lib/active_admin/views/pages/base.rb:86 build_page_content |  
lib/active_admin/views/pages/base.rb:63 block (2 levels) in build_page |  
lib/arbre/element/builder_methods.rb:32 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
lib/arbre/element/builder_methods.rb:15 div |  
lib/active_admin/views/pages/base.rb:59 block in build_page |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:50 with_current_arbre_element |  
lib/active_admin/views/pages/base.rb:58 build_page |  
lib/active_admin/views/pages/base.rb:10 build |  
lib/arbre/element/builder_methods.rb:31 block in build_tag |  
lib/arbre/context.rb:94 with_current_arbre_element |  
lib/arbre/element/builder_methods.rb:27 build_tag |  
lib/arbre/element/builder_methods.rb:40 insert_tag |  
activeadmin (3.2.2) app/views/active_admin/resource/edit.html.arb:3 |  
lib/arbre/context.rb:47 instance_eval |  
lib/arbre/context.rb:47 initialize |  
app/views/active_admin/resource/edit.html.arb:1 new |  
activeadmin (3.2.2) app/views/active_admin/resource/edit.html.arb:1 |  
lib/action_view/base.rb:264 public_send |  
lib/action_view/base.rb:264 _run |  
lib/action_view/template.rb:261 block in render |  
lib/appsignal/hooks/active_support_notifications.rb:19 block in instrument |  
lib/active_support/notifications/instrumenter.rb:58 instrument |  
lib/appsignal/hooks/active_support_notifications.rb:18 instrument |  
lib/action_view/template.rb:549 instrument_render_template |  
lib/action_view/template.rb:249 render |  
lib/action_view/renderer/template_renderer.rb:66 block (2 levels) in render_template |  
lib/appsignal/hooks/active_support_notifications.rb:19 block in instrument |  
lib/active_support/notifications/instrumenter.rb:58 instrument |  
lib/appsignal/hooks/active_support_notifications.rb:18 instrument |  
lib/action_view/renderer/template_renderer.rb:60 block in render_template |  
lib/action_view/renderer/template_renderer.rb:80 render_with_layout |  
lib/action_view/renderer/template_renderer.rb:59 render_template |  
lib/action_view/renderer/template_renderer.rb:11 render |  
lib/action_view/renderer/renderer.rb:63 render_template_to_object |  
lib/action_view/renderer/renderer.rb:31 render_to_object |  
lib/action_view/rendering.rb:135 block in _render_template |  
lib/action_view/base.rb:291 in_rendering_context |  
lib/action_view/rendering.rb:134 _render_template |  
lib/action_controller/metal/streaming.rb:256 _render_template |  
lib/action_view/rendering.rb:121 render_to_body |  
lib/action_controller/metal/rendering.rb:158 render_to_body |  
lib/action_controller/metal/renderers.rb:141 render_to_body |  
lib/abstract_controller/rendering.rb:27 render |  
lib/action_controller/metal/rendering.rb:139 render |  
lib/action_controller/metal/instrumentation.rb:29 block (2 levels) in render |  
vendor/ruby-3.2.2/lib/ruby/3.2.0/benchmark.rb:311 realtime |  
lib/active_support/core_ext/benchmark.rb:14 ms |  
lib/action_controller/metal/instrumentation.rb:29 block in render |  
lib/action_controller/metal/instrumentation.rb:98 cleanup_view_runtime |  
lib/active_record/railties/controller_runtime.rb:39 cleanup_view_runtime |  
lib/action_controller/metal/instrumentation.rb:28 render |  
lib/wicked_pdf/pdf_helper.rb:18 render |  
lib/action_controller/responder.rb:245 default_render |  
lib/action_controller/responder.rb:175 to_html |  
lib/responders/flash_responder.rb:105 to_html |  
lib/action_controller/responder.rb:168 respond |  
lib/action_controller/responder.rb:161 call |  
lib/action_controller/respond_with.rb:216 respond_with |  
lib/inherited_resources/actions.rb:25 edit |  
lib/action_controller/metal/basic_implicit_render.rb:6 send_action |  
lib/abstract_controller/base.rb:224 process_action |  
lib/action_controller/metal/rendering.rb:165 process_action |  
lib/abstract_controller/callbacks.rb:259 block in process_action |  
lib/active_support/callbacks.rb:121 block in run_callbacks |  
lib/turbo-rails.rb:24 with_request_id |  
app/controllers/concerns/turbo/request_id_tracking.rb:10 turbo_tracking_request_id |  
lib/active_support/callbacks.rb:130 block in run_callbacks |  
lib/audited/sweeper.rb:16 around |  
lib/active_support/callbacks.rb:130 block in run_callbacks |  
lib/audited/sweeper.rb:16 around |  
lib/active_support/callbacks.rb:130 block in run_callbacks |  
lib/active_support/callbacks.rb:141 run_callbacks |  
lib/abstract_controller/callbacks.rb:258 process_action |  
lib/action_controller/metal/rescue.rb:25 process_action |  
lib/action_controller/metal/instrumentation.rb:74 block in process_action |  
lib/appsignal/hooks/active_support_notifications.rb:19 block in instrument |  
lib/active_support/notifications/instrumenter.rb:58 instrument |  
lib/appsignal/hooks/active_support_notifications.rb:18 instrument |  
lib/action_controller/metal/instrumentation.rb:73 process_action |  
lib/action_controller/metal/params_wrapper.rb:261 process_action |  
lib/active_record/railties/controller_runtime.rb:32 process_action |  
lib/abstract_controller/base.rb:160 process |  
lib/action_view/rendering.rb:40 process |  
lib/action_controller/metal.rb:227 dispatch |  
lib/action_controller/metal.rb:309 dispatch |  
lib/action_dispatch/routing/route_set.rb:49 dispatch |  
lib/action_dispatch/routing/route_set.rb:32 serve |  
lib/action_dispatch/journey/router.rb:51 block in serve |  
lib/action_dispatch/journey/router.rb:131 block in find_routes |  
lib/action_dispatch/journey/router.rb:124 each |  
lib/action_dispatch/journey/router.rb:124 find_routes |  
lib/action_dispatch/journey/router.rb:32 serve |  
lib/action_dispatch/routing/route_set.rb:882 call |  
lib/rack/protection/base.rb:53 call |  
lib/rack/protection/base.rb:53 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/strategy.rb:202 call! |  
lib/omniauth/strategy.rb:169 call |  
lib/omniauth/builder.rb:44 call |  
lib/rack/attack.rb:127 call |  
lib/warden/manager.rb:36 block in call |  
lib/warden/manager.rb:34 catch |  
lib/warden/manager.rb:34 call |  
lib/rack/tempfile_reaper.rb:20 call |  
lib/rack/etag.rb:29 call |  
lib/rack/conditional_get.rb:31 call |  
lib/rack/head.rb:15 call |  
lib/action_dispatch/http/permissions_policy.rb:36 call |  
lib/action_dispatch/http/content_security_policy.rb:33 call |  
lib/rack/session/abstract/id.rb:272 context |  
lib/rack/session/abstract/id.rb:266 call |  
lib/action_dispatch/middleware/cookies.rb:689 call |  
lib/action_dispatch/middleware/callbacks.rb:29 block in call |  
lib/active_support/callbacks.rb:101 run_callbacks |  
lib/action_dispatch/middleware/callbacks.rb:28 call |  
lib/appsignal/rack/rails_instrumentation.rb:32 call_with_appsignal_monitoring |  
lib/appsignal/rack/rails_instrumentation.rb:17 call |  
lib/action_dispatch/middleware/debug_exceptions.rb:29 call |  
lib/action_dispatch/middleware/show_exceptions.rb:31 call |  
lib/rails/rack/logger.rb:37 call_app |  
lib/rails/rack/logger.rb:24 block in call |  
lib/active_support/tagged_logging.rb:135 block in tagged |  
lib/active_support/tagged_logging.rb:39 tagged |  
lib/active_support/tagged_logging.rb:135 tagged |  
lib/active_support/broadcast_logger.rb:240 method_missing |  
lib/rails/rack/logger.rb:24 call |  
lib/action_dispatch/middleware/remote_ip.rb:92 call |  
lib/request_store/middleware.rb:19 call |  
lib/rack/timeout/core.rb:148 block in call |  
lib/rack/timeout/support/timeout.rb:19 timeout |  
lib/rack/timeout/core.rb:147 call |  
lib/action_dispatch/middleware/request_id.rb:28 call |  
lib/rack/method_override.rb:28 call |  
lib/rack/runtime.rb:24 call |  
lib/action_dispatch/middleware/executor.rb:14 call |  
lib/action_dispatch/middleware/static.rb:25 call |  
lib/rack/sendfile.rb:114 call |  
lib/action_dispatch/middleware/ssl.rb:79 call |  
lib/rack/cors.rb:102 call |  
lib/rails/engine.rb:536 call |  
lib/rack/protection/xss_header.rb:20 call |  
lib/rack/protection/path_traversal.rb:18 call |  
lib/rack/protection/json_csrf.rb:28 call |  
lib/rack/protection/base.rb:53 call |  
lib/rack/protection/base.rb:53 call |  
lib/rack/protection/frame_options.rb:33 call |  
lib/puma/configuration.rb:272 call |  
lib/puma/request.rb:100 block in handle_request |  
lib/puma/thread_pool.rb:378 with_force_shutdown |  
lib/puma/request.rb:99 handle_request |  
lib/puma/server.rb:464 process_client |  
lib/puma/server.rb:245 block in run |  
lib/puma/thread_pool.rb:155 block in spawn_thread


```

**Comment by justinfrench** [comment]
Hey @mateuszbialowas I'm a bit puzzled by this — especially the "sometimes it raises an error" aspect. Can you please confirm if this still an issue for you, and perhaps check if it's still an issue in master?

**Comment by mateuszbialowas** [comment]
@justinfrench  It was not formtastic issue.
